### ISSUE TITLE
discriminacion/abuso extendidos

### ISSUE THREAD

**Issue by ZeroDragon** [eventloop/codigo-de-conducta#2]
En el último chelajs mencionaron "elección de software de desarrollo".  
Sin embargo, no está en el CdC. También a recientes hechos en el slack, se debería extender a "sistema operativo de elección" y yo diría (esto es aporte personal) "Equipo de pokemon go elegido"  
Aunque todos sabemos que #TeamValorMasterRace, pero no hay que ofender a los amarillitos u.u

**Comment by unRob** [comment]
Buen punto, pero me parece que ya se habla de esto en el CdC, al final del primer párrafo:

> Nosotros, los organizadores de JavascriptMX, nos comprometemos a mantener un entorno sin abusos para todo el mundo, sin importar sexo, identidad u orientación sexuales, discapacidad, aspecto físico, edad, raza, nacionalidad o **creencias religiosas**.

[🙃 ](https://xkcd.com/378/)
